all:
  children:
    webservers:
      hosts:
        web1.ru-central1.internal:
          ansible_host: 192.168.20.34
          ansible_user: ubuntu
          ansible_ssh_common_args: '-o ProxyJump=ubuntu@89.169.156.252'
        web2.ru-central1.internal:
          ansible_host: 192.168.30.33
          ansible_user: ubuntu
          ansible_ssh_common_args: '-o ProxyJump=ubuntu@89.169.156.252'

    zabbix:
      hosts:
        zabbix.ru-central1.internal:
          ansible_host: 192.168.10.23
          ansible_user: ubuntu
          ansible_ssh_common_args: '-o ProxyJump=ubuntu@89.169.156.252'

    elk:
      hosts:
        elasticsearch.ru-central1.internal:
          ansible_host: 192.168.20.21
          ansible_user: ubuntu
          ansible_ssh_common_args: '-o ProxyJump=ubuntu@89.169.156.252'
        kibana.ru-central1.internal:
          ansible_host: 192.168.10.6
          ansible_user: ubuntu
          ansible_ssh_common_args: '-o ProxyJump=ubuntu@89.169.156.252'

    bastion:
      hosts:
        bastion.ru-central1.internal:
          ansible_host: 89.169.156.252
          ansible_user: ubuntu
          