---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy Nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: Enable default site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: restart nginx

- name: Deploy test index.html
  copy:
    content: "<h1>Hello from Semioshko Andrey {{ inventory_hostname }}</h1>"
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

