---
# ELK Role Variables

# --- Elasticsearch ---
elasticsearch_version: "7.15.1"
elasticsearch_package_url: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/e/elasticsearch/elasticsearch-{{ elasticsearch_version }}-amd64.deb"
elasticsearch_package_name: "elasticsearch-{{ elasticsearch_version }}-amd64.deb"
elasticsearch_service_name: "elasticsearch"
elasticsearch_port: 9200
# network.host для Elasticsearch будет localhost + IP хоста
# чтобы он был доступен для Kibana/Filebeat внутри сети, но не извне (ограничено SG)
elasticsearch_network_host: "_local_,_site_" # _local_ = 127.0.0.1, _site_ = 192.168.0.0/16, 172.16.0.0/12, 10.0.0.0/8

# --- Kibana ---
kibana_version: "7.15.1"
kibana_package_url: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/k/kibana/kibana-{{ kibana_version }}-amd64.deb"
kibana_package_name: "kibana-{{ kibana_version }}-amd64.deb"
kibana_service_name: "kibana"
kibana_port: 5601
# Kibana должна быть доступна извне, поэтому 0.0.0.0
kibana_server_host: "localhost"

