---
zabbix_repo_url: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb"
zabbix_packages:
  - zabbix-server-mysql
  - zabbix-frontend-php
  - zabbix-nginx-conf
  - zabbix-sql-scripts
  - zabbix-agent
mariadb_packages:
  - mariadb-server
  - mariadb-client
  - python3-pymysql
php_packages:
  - php
  - php-fpm
  - php-mysql
  - php-gd
  - php-xml
  - php-bcmath
  - php-mbstring
  - php-ldap
php_version: "8.1"
zabbix_timezone: "Europe/Moscow"