---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: restart php-fpm
  systemd:
    name: "php{{ php_version }}-fpm"
    state: restarted

- name: restart zabbix-server
  systemd:
    name: zabbix-server
    state: restarted

- name: reload php-fpm
  systemd:
    name: "php{{ php_version }}-fpm"
    state: reloaded